name: epigym
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
  adaptive_icon_foreground: "assets/icon/logo.png"
  adaptive_icon_background: "assets/icon/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/pectoraux.png
    - assets/exercises/Pectoraux/developpe_couche_smith.png
    - assets/exercises/Pectoraux/pompes.png
    - assets/exercises/Pectoraux/ecarte_couche_haltere.png
    - assets/exercises/Pectoraux/dips.png
    - assets/exercises/Pectoraux/pec_deck.png
    - assets/images/biceps.png
    - assets/exercises/biceps/curl_haltere.png
    - assets/exercises/biceps/curl_marteau.png
    - assets/exercises/biceps/curl_barre.png
    - assets/exercises/biceps/curl_poulie.png
    - assets/images/triceps.png
    - assets/exercises/triceps/extension_triceps_corde.png
    - assets/exercises/triceps/skull_crushers.png
    - assets/exercises/triceps/triceps_dips.png
    - assets/images/shoulders.png
    - assets/exercises/shoulders/seated_overhead_press.png
    - assets/exercises/shoulders/lateral_raise_dumbell.png
    - assets/exercises/shoulders/lateral_raise_cable.png
    - assets/exercises/shoulders/face_pull_cable.png
    - assets/images/trapezius.png
    - assets/exercises/Trapezius/rowing_barre.png
    - assets/exercises/Trapezius/rowing_machine.png
    - assets/exercises/Trapezius/shrug_haltere.png
    - assets/exercises/Trapezius/t_bar_row_supported.png