name: epigym
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
  adaptive_icon_foreground: "assets/icon/logo.png"
  adaptive_icon_background: "assets/icon/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/pec.png
    - assets/anatomie/pec/tout_pec.png
    - assets/anatomie/pec/haut_pec.png
    - assets/anatomie/pec/milieu_pec.png
    - assets/anatomie/pec/bas_pec.png
    - assets/exercises/Pectoraux/developpe_couche.png
    - assets/exercises/Pectoraux/pompes.png
    - assets/exercises/Pectoraux/ecarte_couche_haltere.png
    - assets/exercises/Pectoraux/dips.png
    - assets/exercises/Pectoraux/pec_deck.png
    - assets/images/biceps.png
    - assets/exercises/biceps/curl_haltere.png
    - assets/exercises/biceps/curl_marteau.png
    - assets/exercises/biceps/curl_barre.png
    - assets/exercises/biceps/curl_poulie.png
    - assets/images/triceps.png
    - assets/exercises/triceps/extension_triceps_corde.png
    - assets/exercises/triceps/skull_crushers.png
    - assets/exercises/triceps/triceps_dips.png
    - assets/images/shoulders.png
    - assets/exercises/shoulders/seated_overhead_press.png
    - assets/exercises/shoulders/lateral_raise_dumbell.png
    - assets/exercises/shoulders/lateral_raise_cable.png
    - assets/exercises/shoulders/face_pull_cable.png
    - assets/images/trapezius.png
    - assets/exercises/Trapezius/rowing_barre.png
    - assets/exercises/Trapezius/rowing_machine.png
    - assets/exercises/Trapezius/shrug_haltere.png
    - assets/exercises/Trapezius/t_bar_row_supported.png
    - assets/anatomie/trapeze/trapeze.png
    - assets/anatomie/trapeze/haut_trapeze.png
    - assets/anatomie/trapeze/inferieur_trapeze.png
    - assets/anatomie/trapeze/moyen_trapeze.png
    - assets/anatomie/triceps/longue_portion_triceps.png
    - assets/anatomie/triceps/triceps.png
    - assets/anatomie/triceps/vaste_externe_triceps.png
    - assets/anatomie/triceps/vaste_interne_triceps.png
    - assets/anatomie/epaule/arrière_epaule.png
    - assets/anatomie/epaule/avant_epaule.png
    - assets/anatomie/epaule/lateral_epaule.png
    - assets/anatomie/epaule/epaule.png

